version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
  - directory: /.github/workflows
    package-ecosystem: github-actions
    schedule:
      interval: daily