trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - name: Storage
    value: markout
  - name: Container
    value: outlook
  - name: ResourceGroup
    value: app-markout
  - name: Cdn.Profile
    value: sierrasoftworks-markout
  - name: Cdn.Endpoint
    value: markout

stages:
  - stage: build
    displayName: Build Package
    jobs:
      - job: build
        displayName: Build Package
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
            displayName: 'Install Node.js'

          - script: npm install
            displayName: Install NPM Modules
            
          - script: npm test
            displayName: Run NPM Tests

          - script: npm run build
            displayName: Build NPM Package

          - script: |
              cp manifest.xml $(Build.ArtifactStagingDirectory)/manifest.xml
              cp -R assets $(Build.ArtifactStagingDirectory)/
              cp dist/* $(Build.ArtifactStagingDirectory)/
            displayName: 'Prepare Final Package'

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: package
  - stage: release
    displayName: Live
    dependsOn:
      - build
    jobs:
      - deployment: release
        displayName: Release Package
        environment: markout-sierrasoftworks-com
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFileCopy@4
                  displayName: Copy Artifacts to Azure
                  inputs:
                    SourcePath: '$(Pipeline.Workspace)/package'
                    Destination: AzureBlob
                    ContainerName: '$(Container)'
                    azureSubscription: 'MSFT Benefit'
                    storage: $(Storage)
                    sasTokenTimeOutInMinutes: 15
            routeTraffic:
              steps:
                - task: PurgeAzureCDNEndpoint@2
                  displayName: Purge Azure CDN
                  inputs:
                    ConnectedServiceNameSelector: ConnectedServiceNameARM
                    ConnectedServiceNameARM: 'MSFT Benefit'
                    ResourceGroupName: $(ResourceGroup)
                    EndpointName: $(Cdn.Endpoint)
                    ProfileName: $(Cdn.Profile)
                    PurgeContent: '/*'
            postRouteTraffic:
              steps:
                - pwsh: Invoke-WebRequest -UseBasicParsing https://markout.sierrasoftworks.com/outlook/manifest.xml
                  displayName: Confirm Package is Available