trigger:
  - main

resources:
  repositories:
    - repository: templates
      type: github
      name: SierraSoftworks/devops-pipelines
      endpoint: SierraSoftworks

extends:
  template: azurecdn/website.yml@templates
  parameters:
    build:
      - job: build
        displayName: Build Add-in
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
            displayName: 'npm install'
            
          - script: |
              npm test
            displayName: 'npm test'

          - script: |
              npm run build
            displayName: 'npm build'

          - script: |
              cp manifest.xml $(Build.ArtifactStagingDirectory)/manifest.xml
              cp -R assets $(Build.ArtifactStagingDirectory)/
              cp dist/* $(Build.ArtifactStagingDirectory)/
            displayName: 'prepare artifacts'

          - publish: $(Build.ArtifactStagingDirectory)/
            artifact: markout
    pool:
      vmImage: windows-latest
    
    subscription: MSFT Benefit

    # If you've got multiple resource groups, this should match the one used by your CDN profile.
    resourcegroup: app-markout
    cdn_profile: sierrasoftworks-markout

    staging:
      environment: staging-markout-sierrasoftworks-com
      cdn_endpoint: markout
      artifact: markout
      container: outlook-beta
      storage: markout
      healthcheck: https://markout.sierrasoftworks.com/outlook-beta/manifest.xml

    production:
      environment: markout-sierrasoftworks-com
      cdn_endpoint: markout
      artifact: markout
      container: outlook
      storage: markout
      healthcheck: https://markout.sierrasoftworks.com/outlook/manifest.xml
