name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup Node.js environment
      uses: actions/setup-node@v7.0.0
      with:
        node-version: 22.x
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Test Package
      run: npm test

    - name: Build Package
      run: npm run build
